# Generated by Django 4.0.5 on 2022-06-29 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spant_name', models.CharField(max_length=200, verbose_name='Spent identication')),
                ('price', models.FloatField(verbose_name='Price payed')),
                ('dateSpent', models.DateField(verbose_name='Date of expense')),
                ('method_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.people')),
                ('tag_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('people_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.people')),
            ],
        ),
    ]
