# Generated by Django 4.0.5 on 2022-06-29 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spent',
            name='method_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.method_payment'),
        ),
    ]
