# Generated by Django 4.0.5 on 2022-06-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_incoming_dateearn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='dateEarn',
            field=models.DateField(verbose_name='Date of earn'),
        ),
    ]
